# post data login karyawan
###
POST  http://localhost:8000/api/login
Content-Type: application/json

{
    "username" : "ranggax",
    "password" : "rangga105"
}

# get all data Login

###
GET http://localhost:8000/api/data-login
Content-Type: application/json

# get satu data Login

### 
GET http://localhost:8000/api/data-login/rangga
Content-Type: application/json


#post data admin
###
POST  http://localhost:8000/api/login-admin
Content-Type: application/json

{
    "username" : "admins",
    "password" : "administrators"
}

# get all data admin

###
GET http://localhost:8000/api/data-login-admin
Content-Type: application/json

# get satu data admin

### 
GET http://localhost:8000/api/data-login-admin/admins
Content-Type: application/json