# post data login karyawan
###
POST  http://localhost:8000/api/login
Content-Type: application/json

{
    "username" : "ranggax",
    "password" : "rangga105"
}

# get all data Login

###
GET http://localhost:8000/api/data-login
Content-Type: application/json

# get satu data Login

### 
GET http://localhost:8000/api/data-login/rangga
Content-Type: application/json


#post data admin
###
POST  http://localhost:8000/api/login-admin
Content-Type: application/json

{
    "username" : "admins",
    "password" : "administrators"
}

# get all data admin

###
GET http://localhost:8000/api/data-login-admin
Content-Type: application/json

# get satu data admin

### 
GET http://localhost:8000/api/data-login-admin/admins
Content-Type: application/json

#liat semua data barang
###
GET http://toko-barokah.herokuapp.com/api/data-barang
###
POST http://toko-barokah.herokuapp.com/api/data-barang-post
Content-Type: application/json

{
    "code" : "x25",
    "nama" : "Yonex Archsaber 11",
    "kategori" : "raket",
    "harga" : 300000,
    "stock" : 60

}

#Delete Data Barang
###
DELETE http://toko-barokah.herokuapp.com/api/data-barang-delete/3
Content-Type: application/json

# edit barang
###
PUT http://toko-barokah.herokuapp.com/api/data-barang-edit/3
Content-Type: application/json

{
    "code" : "x25s",
    "nama" : "Yonex Archsaber 11s",
    "kategori" : "rakest",
    "harga" : 3000020,
    "stock" : 620

}