#liat semua data barang
###
GET http://toko-barokah.herokuapp.com/api/data-barang
###
POST http://toko-barokah.herokuapp.com/api/data-barang-post
Content-Type: application/json

{
    "code" : "x31",
    "nama" : "Yonex Archsaber 11",
    "kategori" : "raket",
    "merk" : "yonex",
    "harga" : 300000,
    "stock" : 60

}

#Delete Data Barang
###
DELETE http://toko-barokah.herokuapp.com/api/data-barang-delete/3
Content-Type: application/json

# edit barang
###
PUT http://toko-barokah.herokuapp.com/api/data-barang-edit/3
Content-Type: application/json

{
    "code" : "x25s",
    "nama" : "Yonex Archsaber 11s",
    "kategori" : "rakest",
    "harga" : 3000020,
    "merk" : "raket",
    "stock" : 620

}

#liat semua data barang
###
GET http://localhost:8000/api/data-barang
###
POST http://localhost:8000/api/data-barang-post
Content-Type: application/json

{
    "nama" : "Yonex Archsaber 11s",
    "kategori" : "raket",
    "merk" : "yonex",
    "harga" : 3000020
}

#Delete Data Barang
###
DELETE http://localhost:8000/api/data-barang-delete/3
Content-Type: application/json

# edit barang
###
PUT http://localhost:8000/api/data-barang-edit/3
Content-Type: application/json

{
    "code" : "x25s",
    "nama" : "Yonex Archsaber 11s",
    "kategori" : "rakest",
    "harga" : 3000020,

}