###
GET http://toko-barokah.herokuapp.com/api/data-keluar
Content-Type: application/json

###
POST http://toko-barokah.herokuapp.com/api/data-keluar-post
Content-Type: application/json

{
    "code" : "x32",
    "tanggal" : "11/09/2002",
    "nama" : "Yonex Archsaber 11",
    "kategori" : "raket",
    "merk" : "Beat Saber",
    "harga" : 300000,
    "stock" : 60

}

###
PUT http://toko-barokah.herokuapp.com/api/data-keluar-edit/1
Content-Type: application/json

{
    "code" : "x33",
    "tanggal" : "11/09/2007",
    "nama" : "Yonex Archsaber 11",
    "kategori" : "rakets",
    "merk" : "Beat Sabers",
    "harga" : 300000,
    "stock" : 1

}

###
DELETE  http://toko-barokah.herokuapp.com/api/data-keluar-delete/1
Content-Type: application/