# post data login karyawan
###
POST http://localhost:8000/api/login
Content-Type: application/json

{
    "username" : "rangga",
    "password" : "rangga105",
    "nama" : "Siti Fauziah Indriani",
    "status" : "Aktif"
}

###
PUT http://toko-barokah.herokuapp.com/api/data-login-edit/4
Content-Type: application/json

{
    "username" : "ranggaihx",
    "password" : "rangga105",
    "nama" : "Ranggarsy",
    "status" : "Tidak Aktif"
}

# get all data Login

###
GET http://toko-barokah.herokuapp.com/api/data-login
Content-Type: application/json

# get satu data Login

### 
GET http://localhost:8000/api/data-login/rangga
Content-Type: application/json

#Delete data login 

###
DELETE http://localhost:8000/api/data-login-delete/3
Content-Type: application/json


#post data admin
###
POST  http://localhost:8000/api/login-admin
Content-Type: application/json

{
    "username" : "admin",
    "password" : "administrator"
}

# get all data admin

###
GET http://localhost:8000/api/data-login-admin
Content-Type: application/json

# get satu data admin

### 
GET http://localhost:8000/api/data-login-admin/admins
Content-Type: application/json

